### PR TITLE
[Fix] `Symbol.for` is a syntax error in older browsers

### PR DESCRIPTION
**Pull request by ljharb**
For example, Opera 10.6.

Introduced in #204; affects v5.4.0+.

### CODE REVIEW

**Comment by ljharb** [comment]
It seems like buffer v5 doesn't work on old browsers in general, so while I think this would be a good fix, I understand if it's not accepted.

**Comment by feross** [comment]
Thanks for the PR – sorry for the delay in reviewing this. Only issue is a lint error. I will fix post-merge.

**Review by feross — APPROVED** [review]

**Comment by ljharb** [comment]
Awesome, thanks :-)

**Comment by feross** [comment]
Released as 5.7.0.

**Pull request merged**
