### PR TITLE
[WIP] add rw BigInt64 methods

### PR DESCRIPTION
**Pull request by fanatid**
Original issue #244 
This is quick copy code from node. I did not want make everything perfect because have a questions.

Is it ok use let/const/arrow functions/extends/template strings/etc? What if:
1) Package will start use latest syntax and will be transpiled to what should be supported?
2) Package will start use latest syntax and distribute it, so anybody who use it will need traspile to what they actually use? This is not used usually, right? But from my understanding this should give best code for projects who uses buffer, because they will receive only transpiled parts which they not support in their environment.

### CODE REVIEW

**Comment by feross** [comment]
> Is it ok use let/const/arrow functions/extends/template strings/etc?

If we want to continue supporting IE11 that means we can use:

- [let](https://caniuse.com/#feat=let)
- [const](https://caniuse.com/#feat=const) in most places

But should probably avoid the rest.

If we want to use new syntax in the codebase, that would probably let us port code from Node.js more easily, which I like.

But then we need to either:

- drop IE11 and publish a new major version
- add `babel` and start shipping a transpiled build too

**Comment by fanatid** [comment]
Why if we add `babel` we need drop IE11? Not all polyfills work in IE11? Major bump because too much changes?

**Comment by feross** [comment]
@fanatid I meant that we need to do one of those two option.

If we start using new syntax without babel then this package stops working in IE11 unless users start transpiling it. So that's a breaking change and we need to publish a new version.

Or, we use new syntax, add `babel`, and ship a transpiled build. Then no new major version is needed because nothing breaks from the user's perspective.

**Comment by vweevers** [comment]
It might be harder to optimize a transpiled build for performance?

**Comment by feross** [comment]
Yeah, true.

I'm happy to just optimize for newer browsers. The current version of `buffer` works fine in IE11 and folks can always continue using that version if they need IE11 support. We can continue development on a new major version. Let's do it.

**Comment by fanatid** [comment]
Thanks for explanation Feross.
@vweevers probably yes, but continue manually port new code to old syntax is pain for everybody. Other thing that not traspiled code should be executed faster than manually ported because code should be more effective? (but this will break almost all projects who uses buffer? haha)

So, decision is major version bump with new JS features transpiled to supported browsers? :smile:

**Comment by feross** [comment]
I think we should not transpile. Users can do that if they want. We can release a new major version that includes new language features. We shouldn't get carried away, though. Tests should still pass in the last two major versions of every major browser (Chrome, Firefox, Safari, Edge, Safari on iOS, Chrome on Android).

**Comment by java-james** [comment]
When do you think we can expect resolution and merge of this PR?

**Comment by fanatid** [comment]
Sorry, do not have time right now to finish it. Maybe later.

**Comment by collincusce** [comment]
Heyyy do you have time now? This is a feature I could immediately use! <3

**Comment by collincusce** [comment]
@fanatid or @feross there's a lot of missing functions in Buffer and classes like, BN.js which has toArrayLike and tries to use Buffer fails. If this fix patches that, can we get it reviewed and merged?

**Comment by fanatid** [comment]
Can you describe situations (or show examples) when bn.js fails with Buffer?

**Comment by collincusce** [comment]
Absolutely, I should definitely be more clear. I apologize. Using the current nodejs LTS + Typescript, typechecking fails because these functions are missing. This isn't just about BN.js but also things like elliptic. Using any Buffer as a parameter will give an error. Here's some examples of type conflicts. 


Screenshot from 2019-12-14 13-38-15

Screenshot from 2019-12-14 13-29-16

Screenshot from 2019-12-14 13-28-11

**Comment by fanatid** [comment]
Ah, so it's mostly about TypeScript?

**Comment by collincusce** [comment]
Yes sorry if that's not a roadmap item, but it definitely would fix Typescript issues if this push was put in.

**Comment by collincusce** [comment]
Any updates?

**Comment by Tschakki** [comment]
@feross could you merge this one please? :)

**Comment by feross** [comment]
I'm okay with shipping a new version of `buffer` only for modern browsers. We can consider shipping a transpiled version if we want to preserve current browser support, but let's do that in another issue.

@fanatid Do you think this is ready to merge?

**Comment by feross** [comment]
I just tried running the ES6 browser tests and they throw an exception because the way that `assert.throws` is used here:

Screen Shot 2020-06-17 at 5 54 38 PM

Can someone figure out the cause of this? If you do, please either update this PR (@fanatid) or send a PR to this PR (anyone else).

**Comment by collincusce** [comment]
> I'm okay with shipping a new version of buffer only for modern browsers. 

Please! I'm doing so many hokey things to handle Uint64 types lol, and the real barrier here is just getting TypeScript to agree that it's a Buffer class. Without the functions matching, TypeScript balks. Can we make it match the latest nodejs LTS version?

**Comment by fanatid** [comment]
Sorry, I do not have a time to check/update changes =(. Will be happy if somebody fork PR with required fixes / changes.

**Comment by shuse2** [comment]
@feross @fanatid 
I forked thie PR and add a commit to original commit in https://github.com/feross/buffer/pull/267 to address the issue https://github.com/feross/buffer/pull/247#issuecomment-645646172

Running `npm run test-browser-es6-local`, it does not show the thrown error, and still passes the test.

Please check when you have time

**Comment by feross** [comment]
Thanks @shuse2 – let's use #267

**Comment by feross** [comment]
Released as 6.0.0

**Pull request closed without merging**
