### PR TITLE
add missing constants

### LINKED ISSUE #311: Missing buffer.constants.*
There appears to be a missing implementation of 
`buffer.constants.MAX_LENGTH` & `buffer.constants.MAX_STRING_LENGTH` that is documented in the [node buffer api](https://nodejs.org/docs/latest-v14.x/api/buffer.html#buffer_buffer_constants)

### PR DESCRIPTION
**Pull request by urg**
add missing kStringMaxLength, constants.MAX_LENGTH & constants.MAX_STRING_LENGTH

fixes #311

### CODE REVIEW

**Review by dcousens — CHANGES_REQUESTED** [review]
LGTM, but I want a reference for that `2**28 - 1` value.
Reading https://nodejs.org/docs/latest/api/buffer.html#bufferconstantsmax_length , the value seems to be about `2**30-1` on 32-bit architectures.

I think any `buffer` actually near these magnitudes will probably fail no matter, but, if we have a value, it should have a reference.

**Comment by urg** [comment]
@dcousens  - good point on the reference. I can't find where I got the initial value from, however, its now set to what it is in the current version of node.

Please note this is for the max string length and not the max buffer length (https://nodejs.org/docs/latest/api/buffer.html#bufferconstantsmax_string_length). Max buffer length was already defined and just exported to match api spec.

**Review by dcousens — APPROVED** [review]

**Comment by dcousens** [comment]
Thanks for the fast follow up @urg, LGTM!

**Comment by dcousens** [comment]
The tests are passing, the CI has other issues (see https://github.com/feross/buffer/pull/332, I'll be resolving this before the next release).

**Comment by jeremymeng** [comment]
Looks that the typing file hasn't been upgraded to include the newly added constants.

**Comment by dcousens** [comment]
@jeremymeng I have this on my TODO, but I don't have an ETA for you

**Pull request merged**
