### PR TITLE
Fix Chrome 49

### PR DESCRIPTION
**Pull request by LinusU**
See #94, this may or may not be the best approach. At least it works :)

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for the PR, but https://github.com/feross/buffer/issues/94#issuecomment-172131066 says the bug is fixed in Chrome itself, and I can confirm that the tests all pass in Chrome 49.0.2623.0 canary (64-bit, Mac OS X). Closing unless you still think this is an issue, thanks! :)

**Comment by LinusU** [comment]
Great!

**Comment by littledan** [comment]
It'd be great if we could fix this bug in this repo as well. The ES2016 draft spec mandates the behavior that Chrome 49 tries out. Turns out it's not web-compatible yet (due to this particular library and possibly nothing else), but I think it's the most sensible semantics long-term. It'd be great if we could do something in this library so that the web can get the better TypedArray subclassing semantics within a few years.

**Comment by LinusU** [comment]
It probably have to be discussed in Node.js as well, but I think that it's sensible to allow `new Buffer(buffer, start, end)` to create a new slice of another buffer. I'm all for making buffer as similar to typed arrays as possible.

**Pull request closed without merging**
