### PR TITLE
Export missing globals for compat

### PR DESCRIPTION
**Pull request by chjj**

### CODE REVIEW

**Comment by dcousens** [comment]
`Buffer` doesn't export these in node? What's the intent?

**Comment by chjj** [comment]
- https://nodejs.org/docs/latest/api/buffer.html#class-blob
- https://nodejs.org/docs/latest/api/buffer.html#class-file
- https://nodejs.org/docs/latest/api/buffer.html#nodebuffer-module-apis

``` sh
$ node
Welcome to Node.js v21.6.1.
Type ".help" for more information.
> require('buffer').Blob
[class Blob]
> require('buffer').File
[class File extends Blob]
> require('buffer').atob
[Function: atob]
> require('buffer').btoa
[Function: btoa]
```

**Comment by dcousens** [comment]
Interesting, I thought this would be equivalent
```bash
node
Welcome to Node.js v21.6.1.
Type ".help" for more information.
> Buffer.atob
undefined
> require('buffer').atob
[Function: atob]
```

Thanks @chjj

**Comment by dcousens** [comment]
Ah, the global scope only has `Buffer`, nevermind

**Comment by chjj** [comment]
This is silly, but I'm now actually having second thoughts on this one. 

I know this is compatible with browserify as browserify exposes `global` to the module, but I'm curious about other bundlers: parcel/webpack/rollup/esbuild/etc (I know the latter two steer their users towards ES modules, but I think they have some kind of CJS compatibility plugins too?).

Maybe we should switch this to a `typeof x !== 'undefined'` pattern to avoid potentially breaking non-browserify bundlers?

Or maybe I'm just being paranoid and they all support `global`.

**Comment by dcousens** [comment]
I'm happy with the cautious approach, but ideally, can we test this package, in our CI, using some other bundlers?

**Pull request merged**
