### PR TITLE
Switch `BigInt` -> `bigint`

### LINKED ISSUE #296: Cannot find name 'BigInt'
ERROR in node_modules/buffer/index.d.ts:23:38 - error TS2304: Cannot find name 'BigInt'.

23     readBigUInt64LE(offset: number): BigInt;
                                        ~~~~~~
node_modules/buffer/index.d.ts:24:38 - error TS2304: Cannot find name 'BigInt'.

24     readBigUInt64BE(offset: number): BigInt;
                                        ~~~~~~
node_modules/buffer/index.d.ts:30:37 - error TS2304: Cannot find name 'BigInt'.

30     readBigInt64LE(offset: number): BigInt;
                                       ~~~~~~
node_modules/buffer/index.d.ts:31:37 - error TS2304: Cannot find name 'BigInt'.

31     readBigInt64BE(offset: number): BigInt;
                                       ~~~~~~
node_modules/buffer/index.d.ts:45:54 - error TS2304: Cannot find name 'BigInt'.

45     writeBigUInt64LE(value: number, offset: number): BigInt;
                                                        ~~~~~~
node_modules/buffer/index.d.ts:46:54 - error TS2304: Cannot find name 'BigInt'.

46     writeBigUInt64BE(value: number, offset: number): BigInt;
                                                        ~~~~~~
node_modules/buffer/index.d.ts:52:53 - error TS2304: Cannot find name 'BigInt'.

52     writeBigInt64LE(value: number, offset: number): BigInt;
                                                       ~~~~~~
node_modules/buffer/index.d.ts:53:53 - error TS2304: Cannot find name 'BigInt'.

53     writeBigInt64BE(value: number, offset: number): BigInt;
                                                       ~~~~~~
                                                       
It is not able to find BigInt and hence throwing the error on project build. 
"typescript": "^4.0.3"

### PR DESCRIPTION
**Pull request by elibarzilay**
I'm from the group that works on TS --- we ran into a [PR on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54347) that suspiciously required `ESNext.BigInt`, and it looks like it's required by the types declared here.

The thing is that `BigInt` should be replace by `bigint`, in the same way that `number` and `string` should be used instead of `Number` and `String`.

This should also fix #296.

### CODE REVIEW

**Comment by dekadentno** [comment]
Does anyone have a status on this PR?

**Comment by leolcao** [comment]
I verified this PR in my local.

nodejs: 12.22.2
angular: 11.0.1
@types/node: 12.22.2

**Comment by ZumelzuR** [comment]
Why this is closed? was never merged

**Comment by elibarzilay** [comment]
@ZumelzuR, sorry, I made some cleanup of my forks a while ago, and GH took it as a hint to close the PR.  But the change is still recorded here, in case @feross wants to do the fix...

**Pull request closed without merging**
