### PR TITLE
Fix `write{U}Int{LE,BE} types

### PR DESCRIPTION
**Pull request by chronark**
They should take a BigInt as parameter and return the written bytes as regular number, right?

At least that's what it actually does :)

### CODE REVIEW

**Comment by chronark** [comment]
Oh and while we are at it: The `offset` is optional for almost all write methods.
Should I change those too?

**Comment by chronark** [comment]
I just went ahead and matched the optional offsets to the official node implementation.
@feross Can you please review it.

**Review by dcousens — APPROVED** [review]
LGTM,  nice changes @chronark

**Comment by mistermoe** [comment]
any chance this will be merged soon?

**Comment by dcousens** [comment]
@chronark can you restore this fork? I can't merge as you have deleted your fork, but I am happy to merge the changes.
If you can't easily do that, I'll open a new pull request with the changes bundled and ensure attribution is kept in some manner.

**Comment by dcousens** [comment]
See https://github.com/feross/buffer/pull/334

**Pull request closed without merging**
