### PR TITLE
fixed types declaration #213

### PR DESCRIPTION
**Pull request by borovik96**
Changed the way module types are exported. https://github.com/Microsoft/TypeScript/issues/26086#issuecomment-409393394

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR, @borovik96. @ukstv, does this look good to you?

**Comment by makepost** [comment]
Correct and works for me.

**Comment by gabrielrtakeda** [comment]
any update?

**Comment by davidfurlong** [comment]
bump 🙏

**Comment by mrwillis** [comment]
bump :heart:

**Comment by mhh1422** [comment]
When the PR is getting merged?

**Comment by darky** [comment]
Please, merge this as fast as possible!

**Comment by feross** [comment]
Released as 5.2.1

**Comment by mi-mazouz** [comment]
not working for me. It still require @type/nodes/buffer.

Version 5.4.3

**Comment by fandi-komek** [comment]
for me working, using version @types/node@9.6.61

**Pull request merged**
