### PR TITLE
pass Array Buffer to constructor

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by feross** [comment]
We can add support for this feature now that node.js#next has support! https://github.com/nodejs/io.js/pull/2002

**Comment by feross** [comment]
ArrayBuffer can be passed into the constructor as of buffer 3.4.0.

**Comment by calvinmetcalf** [comment]
vindicated! thanks @feross

**Comment by feross** [comment]
@calvinmetcalf Yeah :) I agreed it's a great idea but want to keep this module exactly in sync with node. I argued to support this - happy it finally landed!!

**Pull request closed without merging**
