### PR TITLE
Insert replacement characters like node does when converting UTF8 bytes to String

### PR DESCRIPTION
**Pull request by jessetane**
Possible fix for #66

### CODE REVIEW

**Comment by dcousens** [comment]
Will review today

**Comment by jessetane** [comment]
Cool, thanks. I just installed node@3 and I see now it is replacing things in the surrogate pair range - pushing a test and fix for that now..

**Comment by feross** [comment]
LGTM. Waiting for @dcousens. Feel free to merge when it looks good. Then I'll do a release.

**Comment by dcousens** [comment]
LGTM.  Nice implementation,  I might break down down some of the indentation through the use of `continue`/`break`.

**Comment by feross** [comment]
Published as 3.4.2.

**Pull request merged**
